const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d");
const S={img:null,rect:null,bones:[],mesh:null,selected:null,drag:null,keys:{},time:0,playing:false,adding:false,showMesh:false,showWeights:false};
const uid=()=>Math.random().toString(36).slice(2,8);
const bone=(name,sx,sy,x,y,parent=null)=>({id:uid(),name,sx,sy,x,y,rx:x,ry:y,rsx:sx,rsy:sy,parent});
function pos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function start(b,rest=true){let p=b.parent&&S.bones.find(x=>x.id===b.parent);return p?(rest?{x:p.rx,y:p.ry}:{x:p.x,y:p.y}):(rest?{x:b.rsx,y:b.rsy}:{x:b.sx,y:b.sy})}
function distSeg(px,py,ax,ay,bx,by){let dx=bx-ax,dy=by-ay,L=dx*dx+dy*dy,t=L?((px-ax)*dx+(py-ay)*dy)/L:0;t=Math.max(0,Math.min(1,t));return Math.hypot(px-(ax+t*dx),py-(ay+t*dy))}
function createMesh(){if(!S.rect)return;let C=28,R=22,v=[];for(let j=0;j<=R;j++)for(let i=0;i<=C;i++){let u=i/C,w=j/R;v.push({u,w,rx:S.rect.x+u*S.rect.w,ry:S.rect.y+w*S.rect.h,weights:[]})}S.mesh={C,R,v};bind()}
function bind(){if(!S.mesh||!S.bones.length){document.getElementById("binding").textContent="Image not bound.";return}for(let v of S.mesh.v){let a=S.bones.map(b=>{let s=start(b,true);return{id:b.id,w:1/((distSeg(v.rx,v.ry,s.x,s.y,b.rx,b.ry)+18)**2)}}).sort((a,b)=>b.w-a.w).slice(0,4),sum=a.reduce((n,x)=>n+x.w,0)||1;v.weights=a.map(x=>({id:x.id,w:x.w/sum}))}document.getElementById("binding").className="status ok";document.getElementById("binding").textContent="✓ Image is bound to the bone mesh"}
function deform(v){let X=0,Y=0,W=0;for(let q of v.weights){let b=S.bones.find(x=>x.id===q.id);if(!b)continue;let a=start(b,true),d=start(b,false),ax=b.rx-a.x,ay=b.ry-a.y,bx=b.x-d.x,by=b.y-d.y,la=Math.hypot(ax,ay)||1,lb=Math.hypot(bx,by)||1,co=(ax*bx+ay*by)/(la*lb),si=(ax*by-ay*bx)/(la*lb),px=v.rx-a.x,py=v.ry-a.y;X+=((px*co-py*si)*lb/la+d.x)*q.w;Y+=((px*si+py*co)*lb/la+d.y)*q.w;W+=q.w}return W?{x:X/W,y:Y/W}:{x:v.rx,y:v.ry}}
function tri(a,b,c){let p=deform(a),q=deform(b),r=deform(c),R=S.rect,x0=R.x+a.u*R.w,y0=R.y+a.w*R.h,x1=R.x+b.u*R.w,y1=R.y+b.w*R.h,x2=R.x+c.u*R.w,y2=R.y+c.w*R.h,den=(x1-x0)*(y2-y0)-(x2-x0)*(y1-y0);if(Math.abs(den)<.001)return;let A=((q.x-p.x)*(y2-y0)-(r.x-p.x)*(y1-y0))/den,B=((r.x-p.x)*(x1-x0)-(q.x-p.x)*(x2-x0))/den,C=((q.y-p.y)*(y2-y0)-(r.y-p.y)*(y1-y0))/den,D=((r.y-p.y)*(x1-x0)-(q.y-p.y)*(x2-x0))/den,E=p.x-A*x0-B*y0,F=p.y-C*x0-D*y0;ctx.save();ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.lineTo(r.x,r.y);ctx.closePath();ctx.clip();ctx.setTransform(A,C,B,D,E,F);ctx.drawImage(S.img,0,0,S.img.width,S.img.height,0,0,R.w,R.h);ctx.restore()}
function drawDeformed(){let m=S.mesh;for(let j=0;j<m.R;j++)for(let i=0;i<m.C;i++){let a=m.v[j*(m.C+1)+i],b=m.v[j*(m.C+1)+i+1],c=m.v[(j+1)*(m.C+1)+i+1],d=m.v[(j+1)*(m.C+1)+i];tri(a,b,c);tri(a,c,d)}}
function drawMesh(){if(!S.mesh||!S.showMesh)return;ctx.strokeStyle="rgba(150,130,255,.25)";ctx.lineWidth=1;for(let j=0;j<=S.mesh.R;j++){ctx.beginPath();for(let i=0;i<=S.mesh.C;i++){let v=deform(S.mesh.v[j*(S.mesh.C+1)+i]);i?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y)}ctx.stroke()}for(let i=0;i<=S.mesh.C;i++){ctx.beginPath();for(let j=0;j<=S.mesh.R;j++){let v=deform(S.mesh.v[j*(S.mesh.C+1)+i]);j?ctx.lineTo(v.x,v.y):ctx.moveTo(v.x,v.y)}ctx.stroke()}}
function drawWeights(){if(!S.showWeights||!S.selected||!S.mesh)return;for(let v of S.mesh.v){let w=v.weights.find(q=>q.id===S.selected)?.w||0;if(w>.08){let p=deform(v);ctx.fillStyle=`rgba(255,190,60,${Math.min(.75,w)})`;ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill()}}}
function drawBones(){for(let b of S.bones){let s=start(b,false),sel=b.id===S.selected;ctx.strokeStyle=sel?"#ffd15d":"#8b76ff";ctx.lineWidth=sel?5:3;ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.fillStyle=sel?"#ffd15d":"#9b87ff";ctx.beginPath();ctx.arc(s.x,s.y,5,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(b.x,b.y,8,0,Math.PI*2);ctx.fill();ctx.fillStyle="#eee";ctx.font="12px sans-serif";ctx.fillText(b.name,b.x+10,b.y-8)}}
function render(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);if(S.img&&S.mesh){drawDeformed();drawMesh();drawWeights();document.getElementById("empty").style.display="none"}else document.getElementById("empty").style.display="block";drawBones();renderList();renderInfo();renderKeys()}
function renderList(){let e=document.getElementById("bones");e.innerHTML="";S.bones.forEach(b=>{let d=document.createElement("div");d.className="bone"+(b.id===S.selected?" sel":"");d.textContent="🦴 "+b.name;d.oncontextmenu=x=>{x.preventDefault();deleteBone(b.id)};d.onclick=()=>{S.selected=b.id;render()};e.appendChild(d)})}
function renderInfo(){let b=S.bones.find(x=>x.id===S.selected);document.getElementById("info").innerHTML=b?`<b>${b.name}</b><br>Parent: ${b.parent?"Connected":"Root"}<br>End: ${Math.round(b.x)}, ${Math.round(b.y)}<br><br>Drag the circular end point to change its pose.`:"No bone selected."}
function renderKeys(){let e=document.getElementById("keys");e.innerHTML="";for(let t of Object.keys(S.keys).map(Number).sort((a,b)=>a-b)){let k=document.createElement("div");k.className="key"+(Math.abs(t-S.time)<.006?" current":"");k.style.left=(t/4*100)+"%";k.title=`Keyframe ${t.toFixed(2)}s`;k.onclick=()=>{S.time=t;document.getElementById("time").value=t;applyKeysAtTime();render()};e.appendChild(k)}}
function savePose(){S.keys[S.time]=S.bones.map(b=>({id:b.id,x:b.x,y:b.y}))}
function applyKeysAtTime(){let ts=Object.keys(S.keys).map(Number).sort((a,b)=>a-b);if(!ts.length)return;let a=ts.filter(t=>t<=S.time).pop(),b=ts.find(t=>t>=S.time);if(a===undefined)a=ts[0];if(b===undefined)b=ts.at(-1);let ka=S.keys[a],kb=S.keys[b],u=a===b?0:(S.time-a)/(b-a);for(let p of ka){let bone=S.bones.find(x=>x.id===p.id),q=kb.find(x=>x.id===p.id);if(bone&&q){bone.x=p.x+(q.x-p.x)*u;bone.y=p.y+(q.y-p.y)*u}}}
function deleteBone(id){let doomed=new Set([id]),changed=true;while(changed){changed=false;for(let b of S.bones)if(b.parent&&doomed.has(b.parent)&&!doomed.has(b.id)){doomed.add(b.id);changed=true}}S.bones=S.bones.filter(b=>!doomed.has(b.id));S.selected=S.bones[0]?.id||null;bind();render()}
document.getElementById("import").onclick=()=>document.getElementById("file").click();
document.getElementById("file").onchange=e=>{let f=e.target.files[0];if(!f)return;let im=new Image();im.onload=()=>{S.img=im;let k=Math.min(850/im.width,560/im.height,1);S.rect={x:(1000-im.width*k)/2,y:(650-im.height*k)/2,w:im.width*k,h:im.height*k};createMesh();render()};im.src=URL.createObjectURL(f)};
document.getElementById("autoRig").onclick=()=>{if(!S.img)return alert("Import an image first.");let r=S.rect,x=r.x+r.w/2;S.bones=[bone("Body",x,r.y+r.h*.47,x,r.y+r.h*.25),bone("Head",x,r.y+r.h*.18,x,r.y+r.h*.29),bone("Upper Arm L",x-r.w*.1,r.y+r.h*.43,x-r.w*.02,r.y+r.h*.35),bone("Forearm L",x-r.w*.24,r.y+r.h*.53,x-r.w*.1,r.y+r.h*.43),bone("Upper Arm R",x+r.w*.1,r.y+r.h*.43,x+r.w*.02,r.y+r.h*.35),bone("Forearm R",x+r.w*.24,r.y+r.h*.53,x+r.w*.1,r.y+r.h*.43),bone("Upper Leg L",x-r.w*.07,r.y+r.h*.75,x-r.w*.03,r.y+r.h*.58),bone("Lower Leg L",x-r.w*.09,r.y+r.h*.95,x-r.w*.07,r.y+r.h*.75),bone("Upper Leg R",x+r.w*.07,r.y+r.h*.75,x+r.w*.03,r.y+r.h*.58),bone("Lower Leg R",x+r.w*.09,r.y+r.h*.95,x+r.w*.07,r.y+r.h*.75)];S.bones[1].parent=S.bones[0].id;S.bones[2].parent=S.bones[0].id;S.bones[3].parent=S.bones[2].id;S.bones[4].parent=S.bones[0].id;S.bones[5].parent=S.bones[4].id;S.bones[6].parent=S.bones[0].id;S.bones[7].parent=S.bones[6].id;S.bones[8].parent=S.bones[0].id;S.bones[9].parent=S.bones[8].id;S.selected=S.bones[0].id;bind();render()};
document.getElementById("deleteBone").onclick=()=>S.selected&&deleteBone(S.selected);
document.getElementById("reset").onclick=()=>{S.bones.forEach(b=>{b.x=b.rx;b.y=b.ry});S.time=0;S.keys={};document.getElementById("time").value=0;render()};
document.getElementById("showMesh").onchange=e=>{S.showMesh=e.target.checked;render()};
document.getElementById("showWeights").onchange=e=>{S.showWeights=e.target.checked;render()};
canvas.addEventListener("mousedown",e=>{let p=pos(e),b=S.bones.find(x=>Math.hypot(x.x-p.x,x.y-p.y)<12);if(b){S.selected=b.id;S.drag={b,dx:p.x-b.x,dy:p.y-b.y};render()}});
canvas.addEventListener("mousemove",e=>{if(S.drag){let p=pos(e);S.drag.b.x=p.x-S.drag.dx;S.drag.b.y=p.y-S.drag.dy;render()}});
window.addEventListener("mouseup",()=>S.drag=null);
canvas.addEventListener("contextmenu",e=>{e.preventDefault();let p=pos(e),b=S.bones.find(x=>Math.hypot(x.x-p.x,x.y-p.y)<12);if(b)deleteBone(b.id)});
document.getElementById("addKey").onclick=()=>{savePose();render()};
document.getElementById("time").oninput=e=>{S.time=+e.target.value;applyKeysAtTime();document.getElementById("clock").textContent=S.time.toFixed(2)+"s";render()};
document.getElementById("prev").onclick=()=>{let t=Object.keys(S.keys).map(Number).sort((a,b)=>a-b).filter(x=>x<S.time).pop()??0;S.time=t;document.getElementById("time").value=t;applyKeysAtTime();render()};
document.getElementById("next").onclick=()=>{let t=Object.keys(S.keys).map(Number).sort((a,b)=>a-b).find(x=>x>S.time)??4;S.time=t;document.getElementById("time").value=t;applyKeysAtTime();render()};
document.getElementById("play").onclick=()=>{S.playing=!S.playing;document.getElementById("play").textContent=S.playing?"⏸ Pause":"▶ Play";if(S.playing)tick()};
function tick(){if(!S.playing)return;S.time+=.016;if(S.time>4)S.time=0;document.getElementById("time").value=S.time;document.getElementById("clock").textContent=S.time.toFixed(2)+"s";applyKeysAtTime();render();requestAnimationFrame(tick)}
render();
